### ISSUE TITLE
`focus-group` support `toolbar`

### ISSUE THREAD

**Issue by dmitry-kurmanov** [ai/keyux#17]
based on https://github.com/ai/keyux/issues/9#issue-2151620436

> Add [role="toolbar"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/toolbar_role) support with horizontal default direction.

> As for toolbar it might be a problem because it can contains different types of items e.g. button, spinbutton, checkbox, radio etc - [the toolbar example](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/examples/toolbar/)

**Comment by ai** [comment]
I think we can make test like:

```js
if ((el.target.tagName === 'BUTTON' || e.target.role === 'button' || …) & el.target.closes('[role=toolbar]')) {
```

**Comment by dmitry-kurmanov** [comment]
As I understand, it can contain more control types than only `button`. E.g. `checkbox`, `radiogroup`, or some other type. In general, it can be practically any type.

Anyway, we can start with the `button` support and then extend it on demand.

**Comment by dmitry-kurmanov** [comment]
@ai I will try to implement it if you don't mind.

**Comment by dmitry-kurmanov** [comment]
After some investigation I changed my mind about `el.target.tagName === 'BUTTON'`. I suppose we shouldn't support it. By default button has `submit` type, so to make buttons work properly in the `toolbar` they should have explicitly set of `type="button`. See the [the toolbar example](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/examples/toolbar/) 

That is why I propose not to use the tag selector for the `button`.

**Comment by dmitry-kurmanov** [comment]
Moreover, probably instead of a list of available item types we could support any focusable type via the `node.tabIndex` property. Just select all nodes from the toolbar: `toolbarGroup.querySelectorAll("*")` and then filter it by `tabIndex` property existence.

What do you think about the idea?

**Comment by ai** [comment]
> After some investigation I changed my mind about el.target.tagName === 'BUTTON'. I suppose we shouldn't support it. By default button has submit type, so to make buttons work properly in the toolbar they should have explicitly set of type="button. See the [the toolbar example](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/examples/toolbar/)

OK

> Moreover, probably instead of a list of available item types we could support any focusable type via the node.tabIndex property.

Adding `tabindex` on `button`/`input`/`a` looks not very elegant.

**Comment by dmitry-kurmanov** [comment]
> > After some investigation I changed my mind about el.target.tagName === 'BUTTON'. I suppose we shouldn't support it. By default button has submit type, so to make buttons work properly in the toolbar they should have explicitly set of type="button. See the [the toolbar example](https://www.w3.org/WAI/ARIA/apg/patterns/toolbar/examples/toolbar/)
> 
> OK
> 
> > Moreover, probably instead of a list of available item types we could support any focusable type via the node.tabIndex property.
> 
> Adding `tabindex` on `button`/`input`/`a` looks not very elegant.

I removed the comment because the "tabindex idea" will not work. We set `tabindex='-1'` to prevent extra tab focus while we are inside the `focus-group`. I will think how to implement it.
