### ISSUE TITLE
Add video demo to `README.md`

### ISSUE THREAD

**Issue by ai** [ai/keyux#23]
We need a video of using https://ai.github.io/keyux/ with:

1. Press Alt+B (or Cmd+B on Mac) a few times
2. Press Tabs twice to move focus to menu
3. Press → and ← to see key navigation inside focus group
4. Press `a` and `b` to show quick search inside menu
5. Press enter to show focus jump on next submenu
6. Press `Esc` to go back
7. Press `l` and `i` to select `List1`
8. Press Enter
9. Press `v` to click first button
10. Press ↓ to go to the next button
11. Press `v` to show local hotkeys
12. Press `Esc`

The video should:
- Be in h264/mp4 format without sound
- Do not contain browser frame, etc. It should have small dimensions as possible.
- Show what key was pressed
- Find a right timing to be dynamic but understandable

**Comment by uzurpastor** [comment]
PR: #27
