### ISSUE TITLE
Usage within `aria-hidden="true"`

### ISSUE THREAD

**Issue by vitalybaev** [ai/keyux#41]
I have a regular web UI where I use `keyux` to detect hotkeys from `aria-keyshortcuts`.
But, when I open a modal window, all shortcuts from hidden by modal are still active, which led to some confusion.

Modal is done by `Radix-UI` and I suppose that it follows the best a11y practices and adds `aria-hidden="true"` to all content underneath the modal.

I'm not a professional in the a11y, but shouldn't `keyux` stop listening for that shortcuts within `aria-hidden="true"` or not? Just logically and based on `aria-hidden="true"` intention - such events shouldn't be listened, since if we hide content for one audience (screen readers users), we shouldn't let others use it without any restrictions.

If `keyux` should stop reacting to such events, I can contribute to it, if it's shouldn't, what is the best strategy to handle this?
Thanks!

**Comment by ai** [comment]
Does it set `inert` attribute on the page outside of the modal?

`inert` is the right method to disable some part of the page and I suggest using it.

**Comment by ai** [comment]
Yes, we need to add `inert`

**Comment by ai** [comment]
I pushed the fix 7566fe8

Can you test that it works in your case?

```sh
pnpm remove keyux
pnpm add keyux@ai/keyux
```

If yes, I will release it today.

**Comment by vitalybaev** [comment]
Yes, it works perfectly

**Comment by ai** [comment]
Released in 0.9.0
